user.create=API to create a new user.
user.getById=API to get user details by user ID.
user.getAll=API to get all available users.
user.update=API to update user details by user ID.
user.delete=API to delete a user by user ID.